### PR TITLE
(#feat): Improved oop style aspect declaration

### PR DESCRIPTION
**Pull request by konstantinkrassmann**
This is the pull for the feature request: #4

### CODE REVIEW

**Comment by amoilanen** [comment]
Thank you for the contribution, nice improvements. I will merge the changes. The existing API is indeed quite low level, I wanted to provide more syntactic sugar and shorter ways to apply aspects after a few examples of library usage have been written.

**Comment by amoilanen** [comment]
After merging I did also a bit of re-factoring b3370ad38a...ff4f1f3e52 of the test and code. Please, let me know if you have any suggestions.

**Comment by konstantinkrassmann** [comment]
For me, this is now sugar :+1: 

Moving the method `applyTo` to the Aspect -> :+1: 
Multiple arguments, instead of an array at Aspect -> :+1: 

But for me, a `new jsAspect.Before` is not self explaining enought. 
Maybe adding a package/namespace for Advices:

`new jsAspects.Advice.Before()`

**Comment by amoilanen** [comment]
The namespace for Advices was added like it was suggested in 85164fa553bf1f94ae07ae2dd4c0630df68a03f3

**Pull request merged**
